imports:
    - { resource: controllers.yml }

parameters:
    edgarez.uiinfobundles.packagist.api.list: "https://packagist.org/packages/list.json?type=<type>"
    edgarez.uiinfobundles.packagist.api.package: "https://packagist.org/p/<vendor>/<name>.json"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUIInfoBundles\API\PackagistAPI:
        public: true
        arguments:
            $listPackageUrl: "%edgarez.uiinfobundles.packagist.api.list%"
            $packageInfoUrl: "%edgarez.uiinfobundles.packagist.api.package%"

    Edgar\EzUIInfoBundlesBundle\Cron\BundlesCron:
        tags:
          - { name: "edgar.cron", arguments: "type:ezplatform-bundle", alias: bundles, priority: 100, expression: "0 * * * *" }

    Edgar\EzUIInfoBundlesBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }

    Edgar\EzUIInfoBundles\Form\Type\VendorChoiceType: ~
