global:
    system_info_view:
        pjax_tab:
            bundles:
                template: 'EdgarEzUIInfoBundlesBundle:admin/systeminfo:bundles.html.twig'
                match:
                    SystemInfo\Identifier: 'bundles'
